/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;



/**
 *
 * @author SHIRLEY
 */
public class Form_Clientes extends javax.swing.JPanel {

    private Modelo.Cliente clienteSeleccionado;
    private boolean modoEdicion = false;

    /**
     * Creates new form JPanel_Clientes
     */
    public Form_Clientes() {
        initComponents();
        setCamposHabilitados(false); // Deshabilitar campos al iniciar
        configurarComboTipoEmpresa(); //  Configurar combo
        cargarClientesEnTabla(); //  Mostrar todos los clientes al iniciar
        configurarSeleccionTabla(); // Configurar listener para selección de tabla
        txt_buscarRuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String ruc = txt_buscarRuc.getText().trim();
                if (ruc.isEmpty()) {
                    cargarClientesEnTabla();
                    return;
                }
                String[] titulos = {"ID", "RUC/DNI", "Empresa", "Tipo Empresa", "Ciudad", "Dirección", "Correo", "Teléfono", "Personal Contacto"};
                javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, titulos);
                try {
                    for (Modelo.Cliente c : DAO.DAOFactory.getClienteDAO().findAll()) {
                        if (c.getRucDni().toLowerCase().contains(ruc.toLowerCase())) {
                            Object[] fila = new Object[9];
                            fila[0] = c.getIdCliente();
                            fila[1] = c.getRucDni();
                            fila[2] = c.getNombreEmpresa();
                            fila[3] = c.getTipoEmpresa();
                            fila[4] = c.getCiudad();
                            fila[5] = c.getDireccion();
                            fila[6] = c.getCorreo();
                            fila[7] = c.getTelefonoContacto();
                            fila[8] = c.getPersonalContacto();
                            modelo.addRow(fila);
                        }
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(Form_Clientes.this, "Error al buscar clientes: " + e.getMessage());
                }
                tbl_usuario.setModel(modelo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPersonalContacto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbTipoEmpresa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lbl_ingresarDNI = new javax.swing.JLabel();
        txt_buscarRuc = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuario = new javax.swing.JTable();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(1128, 554));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gestión de Clientes");

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personal de Contacto:");

        txtPersonalContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonalContactoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RUC:");

        txtRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Empresa:");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de Empresa:");

        cmbTipoEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEmpresaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ciudad:");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Código Postal:");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección:");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Correo:");

        lbl_ingresarDNI.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lbl_ingresarDNI.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingresarDNI.setText("Buscar cliente(RUC):");

        txt_buscarRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarRucActionPerformed(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(25, 25, 25));
        btn_nuevo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Nuevo1.png"))); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        tbl_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_usuario);

        btn_guardar.setBackground(new java.awt.Color(25, 25, 25));
        btn_guardar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Guardar.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(25, 25, 25));
        btn_eliminar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eliminar.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_nuevo)
                                .addGap(62, 62, 62)
                                .addComponent(btn_guardar)
                                .addGap(70, 70, 70)
                                .addComponent(btn_eliminar))
                            .addComponent(lbl_ingresarDNI)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPersonalContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_buscarRuc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel9)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPersonalContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lbl_ingresarDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_buscarRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevo)
                    .addComponent(btn_guardar)
                    .addComponent(btn_eliminar))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucActionPerformed

    private void cmbTipoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoEmpresaActionPerformed

    // Método para habilitar/deshabilitar campos
    private void setCamposHabilitados(boolean habilitado) {
        txtPersonalContacto.setEnabled(habilitado);
        txtRuc.setEnabled(habilitado);
        txtEmpresa.setEnabled(habilitado);
        txtTelefono.setEnabled(habilitado);
        cmbTipoEmpresa.setEnabled(habilitado);
        txtCiudad.setEnabled(habilitado);
        txtCodigoPostal.setEnabled(habilitado);
        txtDireccion.setEnabled(habilitado);
        txtCorreo.setEnabled(habilitado);
    }

    // Configurar el combo con las opciones correctas
    private void configurarComboTipoEmpresa() {
        cmbTipoEmpresa.removeAllItems();
        cmbTipoEmpresa.addItem("Corporativo");
        cmbTipoEmpresa.addItem("Distribuidor");
        cmbTipoEmpresa.addItem("Minorista");
    }

    //  Limpiar los campos
    private void limpiarCampos() {
        txtPersonalContacto.setText("");
        txtRuc.setText("");
        txtEmpresa.setText("");
        txtTelefono.setText("");
        cmbTipoEmpresa.setSelectedIndex(-1);
        txtCiudad.setText("");
        txtCodigoPostal.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
    }

    //  Cargar todos los clientes en la tabla
    private void cargarClientesEnTabla() {
        try {
            javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"RUC/DNI", "Tipo Empresa", "Ciudad", "Empresa", "Código Postal", "Dirección", "Correo", "Teléfono", "Personal Contacto"}
            );
            Servicio.SistemaFacade facade = new Servicio.SistemaFacade();
            java.util.List<Modelo.Cliente> clientes = facade.listarClientes();
            for (Modelo.Cliente c : clientes) {
                modelo.addRow(new Object[]{
                    c.getRucDni(),
                    c.getTipoEmpresa(),
                    c.getCiudad(),
                    c.getNombreEmpresa(),
                    c.getCodigoPostal(),
                    c.getDireccion(),
                    c.getCorreo(),
                    c.getTelefonoContacto(),
                    c.getPersonalContacto()
                });
            }
            tbl_usuario.setModel(modelo);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar clientes: " + e.getMessage());
        }
    }

    // Buscar cliente por RUC/DNI
    private void buscarClientePorRucDni(String rucDni) {
        try {
            javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"RUC/DNI", "Tipo Empresa", "Ciudad", "Empresa", "Código Postal", "Dirección", "Correo", "Teléfono", "Personal Contacto"}
            );
            Servicio.SistemaFacade facade = new Servicio.SistemaFacade();
            Modelo.Cliente cliente = facade.buscarClientePorRucDni(rucDni);
            if (cliente != null) {
                modelo.addRow(new Object[]{
                    cliente.getRucDni(),
                    cliente.getTipoEmpresa(),
                    cliente.getCiudad(),
                    cliente.getNombreEmpresa(),
                    cliente.getCodigoPostal(),
                    cliente.getDireccion(),
                    cliente.getCorreo(),
                    cliente.getTelefonoContacto(),
                    cliente.getPersonalContacto()
                });
            }
            tbl_usuario.setModel(modelo);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar cliente: " + e.getMessage());
        }
    }

 

    
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Servicio.SistemaFacade facade = new Servicio.SistemaFacade();
            
            if (modoEdicion && clienteSeleccionado != null) {
                // Modo actualización
                actualizarClienteDesdeCampos();
                facade.actualizarCliente(clienteSeleccionado);
                javax.swing.JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente");
            } else {
                // Modo creación
                Modelo.Cliente cliente = new Modelo.Cliente();
                cliente.setRucDni(txtRuc.getText());
                cliente.setTipoEmpresa((String) cmbTipoEmpresa.getSelectedItem());
                cliente.setCiudad(txtCiudad.getText());
                cliente.setNombreEmpresa(txtEmpresa.getText());
                cliente.setCodigoPostal(txtCodigoPostal.getText());
                cliente.setDireccion(txtDireccion.getText());
                cliente.setCorreo(txtCorreo.getText());
                cliente.setTelefonoContacto(txtTelefono.getText());
                cliente.setPersonalContacto(txtPersonalContacto.getText());
                facade.registrarCliente(cliente);
                javax.swing.JOptionPane.showMessageDialog(this, "Cliente guardado correctamente");
            }
            
            setCamposHabilitados(false);
            limpiarCampos();
            clienteSeleccionado = null;
            modoEdicion = false;
            cargarClientesEnTabla();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar cliente: " + e.getMessage());
        }
    }

    
    private void actualizarClienteDesdeCampos() {
        clienteSeleccionado.setRucDni(txtRuc.getText());
        clienteSeleccionado.setTipoEmpresa((String) cmbTipoEmpresa.getSelectedItem());
        clienteSeleccionado.setCiudad(txtCiudad.getText());
        clienteSeleccionado.setNombreEmpresa(txtEmpresa.getText());
        clienteSeleccionado.setCodigoPostal(txtCodigoPostal.getText());
        clienteSeleccionado.setDireccion(txtDireccion.getText());
        clienteSeleccionado.setCorreo(txtCorreo.getText());
        clienteSeleccionado.setTelefonoContacto(txtTelefono.getText());
        clienteSeleccionado.setPersonalContacto(txtPersonalContacto.getText());
    }

    
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {
        int fila = tbl_usuario.getSelectedRow();
        if (fila >= 0) {
            String rucDni = (String) tbl_usuario.getValueAt(fila, 0);
            try {
                Servicio.SistemaFacade facade = new Servicio.SistemaFacade();
                Modelo.Cliente cliente = facade.buscarClientePorRucDni(rucDni);
                if (cliente != null) {
                    facade.marcarClienteComoInactivo(cliente.getIdCliente());
                    javax.swing.JOptionPane.showMessageDialog(this, "Cliente marcado como inactivo correctamente");
                    cargarClientesEnTabla();
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al marcar cliente como inactivo: " + e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente para eliminar");
        }
    }

    
    private void txt_buscarRucActionPerformed(java.awt.event.ActionEvent evt) {
        String rucDni = txt_buscarRuc.getText();
        if (!rucDni.trim().isEmpty()) {
            buscarClientePorRucDni(rucDni);
        } else {
            cargarClientesEnTabla();
        }
    }

    private void txtPersonalContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonalContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonalContactoActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        setCamposHabilitados(true);
        limpiarCampos();
        clienteSeleccionado = null;
        modoEdicion = false;
    }//GEN-LAST:event_btn_nuevoActionPerformed

    // Configurar listener para selección en tabla
    private void configurarSeleccionTabla() {
        tbl_usuario.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = tbl_usuario.getSelectedRow();
                if (fila != -1) {
                    cargarClienteSeleccionado(fila);
                }
            }
        });
    }

    
    private void cargarClienteSeleccionado(int fila) {
        try {
            String rucDni = (String) tbl_usuario.getValueAt(fila, 0);
            Servicio.SistemaFacade facade = new Servicio.SistemaFacade();
            clienteSeleccionado = facade.buscarClientePorRucDni(rucDni);
            
            if (clienteSeleccionado != null) {
                // Cargar datos en los campos
                txtRuc.setText(clienteSeleccionado.getRucDni());
                cmbTipoEmpresa.setSelectedItem(clienteSeleccionado.getTipoEmpresa());
                txtCiudad.setText(clienteSeleccionado.getCiudad());
                txtEmpresa.setText(clienteSeleccionado.getNombreEmpresa());
                txtCodigoPostal.setText(clienteSeleccionado.getCodigoPostal());
                txtDireccion.setText(clienteSeleccionado.getDireccion());
                txtCorreo.setText(clienteSeleccionado.getCorreo());
                txtTelefono.setText(clienteSeleccionado.getTelefonoContacto());
                txtPersonalContacto.setText(clienteSeleccionado.getPersonalContacto());
                
                // Habilitar campos para edición
                setCamposHabilitados(true);
                modoEdicion = true;
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar cliente: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JComboBox<String> cmbTipoEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ingresarDNI;
    private javax.swing.JTable tbl_usuario;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtPersonalContacto;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txt_buscarRuc;
    // End of variables declaration//GEN-END:variables
}
